### ISSUE TITLE
Slow Compiling

### ISSUE THREAD

**Issue by skillmatic-co** [ConnectThink/WP-SCSS#100]
Other people seem to be having this issue as well, but WP-SCSS is now compiling very slowly since the last version. I'm currently on version 1.2.3. For every CSS change, the next page reload is VERY slow now. Causing slowed development. What is the fix here? Also referencing [this Wordpress.org thread](https://wordpress.org/support/topic/slow-loading-since-last-update/).

**Comment by tenold** [comment]
The blogs I build are all relatively the same and this never happened until the latest update.

**Comment by brrn** [comment]
We aren't running into any slow compiling issues either. Can you give us some more detail around your setup?

**Comment by tenold** [comment]
The themes I build are based on Underscores (https://underscores.me). Just wanted to be clear though, this wasn't happening on a site that I have been working on. Once I updated to this version, every time I modify CSS a page load is taking 30-60 seconds. So nothing changed with my CSS, the only change was this plugin.

**Comment by brrn** [comment]
Are you referring to the latest release where we updated to scssphp version 0.7.2? That is the library this plugin uses to compile scss and we don't touch that code, we only include it. It might make sense for you to just use an earlier version for now.

We do have a new version coming out shortly which will include scssphp 0.7.5. Maybe that will compile faster for you.

**Comment by tenold** [comment]
I'm assuming then that it has to be something in scssphp 0.7.2. I'm not the only one having this issue, as you can see in the original post, I include a thread from the Wordpress.org forums where at least a couple others have the same issue with the latest version.

I will dig through the issues on https://github.com/leafo/scssphp/ and see if I can find anything there.

**Comment by tenold** [comment]
This is an older issue, but could be a culprit as it's still an open issue:

https://github.com/leafo/scssphp/issues/527

I do use base64 embedded data with custom fonts.

So before version 1.2.3, WP-SCSS was using scssphp version 0.6.6, which was before the issue above was created.

So what I'm guessing is something changed in scssphp after version 0.6.6 that caused this slowdown.

Is there a way to download version 1.2.2 of WP-SCSS?

**Comment by garrettw** [comment]
Grab the zip file of the tree at [this commit](https://github.com/ConnectThink/WP-SCSS/tree/e4a43df66f166cc202d8aa346f0cccc85a4d3d17).

**Comment by brrn** [comment]
Thanks @garrettw. I just realized we haven't been using releases properly. We will be sure to do so in the future.

@tenold I'll bump the thread you referenced.

**Comment by katipierson** [comment]
Same problem here. If i activate the plugin. The TTFB increase to 4 seconds.
After i deactivate the plugin. All works fine with 190ms.

**Comment by tenold** [comment]
Any other alternative SCSS compiling plugins? This has come to a halt with me. I can't deal with the slow loading anymore.

**Comment by shadoath** [comment]
As we have started our migration to ScssPhp from the deprecated leafo/scss I think this is or will soon be a non issue.
Let me know if this still comes up in the newest version of WP-SCSS.

**Comment by Shimonsta** [comment]
For WP-SCSS slow load, try updating your php version... Worked for me...

**Comment by gcwebsites** [comment]
> For WP-SCSS slow load, try updating your php version... Worked for me...

This didn't make a difference for me.

**Comment by shadoath** [comment]
@Shimonsta & @gcwebsites What version were you on and what did you upgrade to?

**Comment by gcwebsites** [comment]
> @Shimonsta & @gcwebsites What version were you on and what did you upgrade to?
The latest version - Version 2.4.0

PHP 7.4 and even PHP 8.0 hasn't had an improvement. I have posted this with no luck - https://github.com/ConnectThink/WP-SCSS/issues/225

**Comment by katipierson** [comment]
> For WP-SCSS slow load, try updating your php version... Worked for me...

I think this advice is only useful to a limited extent.

Nikita Popov and several other PHP core developers are improving PHP from version to version. As a result, particularly bad code has really gained a lot in terms of performance.

A good example of this is Wordpress - it is interesting to see how the performance increases if you only change the PHP version under a Wordpress installation. But even that doesn't improve Wordpress by the 10-20 seconds that WP-SCSS adds to the Wordpress installation.

The code has a performance problem somewhere and a PHP update cannot really solve it. At most it is a workaround.

In addition, it is not always possible to change the PHP version, e.g. if you have a customer system or other dependencies in your scripts.

I rather suspect that you don't have "Always recompile" active. If I disable that, then the loading time in the backend is only 2-3 seconds. But if you actively develop the styling, the CSS will unfortunately not compile fast enough.

I have had the problem again since the last versions and slows the backend down between 8 and 20 seconds.

I updated the ScssPHP version via Composer, but that doesn't help either.

If I only implement SCSSPHP myself, then the compilation is relatively quick. In my opinion, the performance killer is somewhere in the plugin. But I haven't debugged that now.
