### ISSUE TITLE
Optimizing of id selectors

### ISSUE THREAD

**Issue by NilsHoyer** [ConnectThink/WP-SCSS#145]
I wrote my .scss hierarchical like given in my HTML code. For example:

```
body {
  #header {
    background: blue;
  }
  #main {
    blackground: yellow;
  }
  #footer {
    background: green;
  }
}
```

This is easy to read for me.

But the generated .css file has unneeded code:

```
body #header {
  background: blue;
}
body #main {
  background: yello;
}
body #footer {
  background: green;
}
```

Since each id is allowed one time only inside the HTML code, it's unneeded to write the `body` tag name here. It could be more simple:

```
#header {
  background: blue;
}
#main {
  background: yello;
}
#footer {
  background: green;
}
```

So I wish to have an optimization with removing tags and classes in front of ids in the generated .css file.

Since I didn't want to bother you with this, I thought to implement this by myself. But I miss a final WordPress filter after compilation to implement this easily.

Maybe you can add the requested optimization or the required filter?

**Comment by garrettw** [comment]
1. This does not pertain to WP-SCSS but rather the underlying library, [scssphp](scssphp), which is the interpreter.
2. scssphp aims to achieve parity with the other SCSS interpreters, and they do not do what you are asking for.
3. This "optimization" is not always desirable because it changes the specificity of the selector from your original code.
4. There are other valid purposes for pairing other selectors with IDs that you seemingly have not thought of.
5. If you want cleaner CSS, write cleaner SCSS. One of the basic principles is that you should avoid unnecessary nesting, because it will all be included in the output.

**Comment by NilsHoyer** [comment]
> If you want cleaner CSS, write cleaner SCSS.

I believe, you didn't read my wish carefully, so I will mention the important part of it again:

>  I miss a final WordPress filter after compilation

**Comment by garrettw** [comment]
I believe you missed my point. My point was that you shouldn't be doing this anyway, and you should be writing your SCSS in such a way as to not need this transformation.

**Comment by NilsHoyer** [comment]
You don't want to implement my feature request, I understood. But I will not comment your opinion.
