### ISSUE TITLE
Error after 2.1.1 : Fatal error

### ISSUE THREAD

**Issue by Bsoubrevilla** [ConnectThink/WP-SCSS#172]
Hey,

I actualy got a problem with WP-SCSS.

When i try to use a version post 2.0.0 i got a fatal error like : Fatal error: Uncaught Error: Class '' not found in /home/merlin2/public_html/wp-content/plugins/wp-scss/scssphp/src/Compiler.php:244.

Anyone has an idea about how to fix it please ?

Basil

**Comment by shadoath** [comment]
Please use version 2.1.3 or 2.1.4 There was a bug introduced in 2.1.1 You can read the full thread in issue #168

**Comment by Bsoubrevilla** [comment]
Hello,

I tried to use version 2.1.4 but still the same problem.

It's an OVH hosted site.

**Comment by stevearbour** [comment]
Yes, I am having the same issue, why is this issue closed ?

**Comment by shadoath** [comment]
I'll need more information to be able to diagnose and fix it. What is your PHP version? Anything else that you can provide about your env would help.  
Because it is the scssphp/compiler.php it may be that the upgrade to the new version in 2.0 introduced some different compiler issues. I'm working to update the core ScssPhp version and will do so in steps.
For now, you may want to jump back to [1.2.6 of WP-SCSS](https://github.com/ConnectThink/WP-SCSS/releases/tag/1.2.6)

**Comment by Bsoubrevilla** [comment]
Ok, after serveral tests, i found out a part of the problem.

My template is based on ACF, but when i disable the plugin, WP-SCSS works. I don't have time right now to run more tests, but i'll look a bit more this afternoon i hope.

**Comment by Bsoubrevilla** [comment]
I discovered the origin ! It's not about ACF, but a condition to disable the recompilation. I have a Yes/No in my back office 

//Always recompile
if(function_exists('get_field') && get_field('mode_developpement', 'options')):
  define('WP_SCSS_ALWAYS_RECOMPILE', true); 
endif;

So my problem is about that WP_SCSS_ALWAYS_RECOMPILE.
