### ISSUE TITLE
Improving performance

### ISSUE THREAD

**Issue by gcwebsites** [ConnectThink/WP-SCSS#225]
Hi Team,

Any idea how to improve compiling performance? My site is taking like 15 seconds to compile the CSS.

It is running on a Linode Dedicated 64 GB server. Any specific PHP settings that should be increased? PHP Memory is already at 6048MB.

Any other recommendations?

Thanks.

**Comment by gcwebsites** [comment]
Any idea? I have optimised some of my SCSS code but still not having much luck. It seems weird as WP Engine is a lot faster when recompiling stuff!

**Comment by katipierson** [comment]
I have the same problem since the last versions.

Important: "always recompile" is active.

I tried the following:
1) SCSSPHP updated - that brought no improvement - except that the latest bootstrap version is now compiled.
2) PHP version update: No improvement.
3) Plugin "WP-SCSS" deactivated and SCSSPHP implemented directly. Worked fine. Disadvantage: The settings are not available.

Since SCSSPHP works without the plugin, I suspect the performance killer in the plugin.

**Comment by gcwebsites** [comment]
> Since SCSSPHP works without the plugin, I suspect the performance killer in the plugin.

I think so too. I am having the same issue. I like the plugin because of the Source Map option.

**Comment by shadoath** [comment]
Would like to work on this by looking at benchmarks and timing checks.  Can you provide info about how many SCSS files you have and how many lines of code? Even better would be if you can share those so I can test on something similar to what is causing the 10-20 seconds slower loads.

**Comment by katipierson** [comment]
@shadoath 
You can use a normal bootstrap. I already have the problem with a Wordpress + WP-SCSS and an empty theme that only loads the CSS. I have all bootstrap components enabled.

You can find it here: https://github.com/twbs/bootstrap/releases
I load it via Composer, but both sources should be identical.

Unfortunately, I can't share a project because both are customer projects.

Only the hook "Always recompile" is important.
