### ISSUE TITLE
Add ability to Compile different file name 

### ISSUE THREAD

**Issue by ismailfarooq-10p** [ConnectThink/WP-SCSS#79]
I am using this command on my local `--watch scss/main.scss:css/style.css` but i am not able to compile main.scss to style.css is there any solution for this ?

For example:
Scss Location: /scss/main.scss
CSS Location: /css/style.css

**Comment by garrettw** [comment]
This is a WordPress plugin that includes the PHP implementation of the SCSS parser.
It is not usable from the command line.

If you have configured the SCSS and CSS directories in this plugin's settings, then simply loading a page on your site will trigger the compilation process.

**Comment by ismailfarooq-10p** [comment]
No No i am asking to add option for filename 

**For example:
Scss Location: /scss/main.scss
CSS Location: /css/style.css**

Currently we can just add directory path hope you got

**Comment by garrettw** [comment]
The reason you can only set the directory path is that this plugin will compile *all* SCSS files found in that directory into CSS files. And if you had to specify the name for one set of files, you would have to specify the name for all of the files you would potentially have.

So just compiling to a similar file name makes it easier - and it's better for the developer because they can tell which SCSS file became which CSS file more easily.

**Comment by viveksaroch** [comment]
use `@import` method and import your `main.scss` in `style.scss` and compile it into `style.css`

**Comment by garrettw** [comment]
@ismailfarooq-10p As this is feature is not likely to be added, if the above suggestion solves your problem, would you mind closing this issue?
